preprocess:
  input: data/raw/data.csv
  output: data/processed/data.csv

train:
  data: "data/raw/data.csv"
  model: "models/model.pkl"
  random_state: 42
  n_estimators: [100, 200]
  max_depth: [5, 10]
  min_samples_split: [2, 5]
  min_samples_leaf: [1, 2]